version: '3.8'
services:
  nodejs:
    build: .
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PGHOST=db
      - PGUSER=admin
      - PGDATABASE=marketdb
      - PGPASSWORD=1234
      - PGPORT=5432
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=marketdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: